apiVersion: v1
kind: Pod
metadata:
  name: flask-app-2
spec:
  containers:
  - name: flask-app-2
    image: appan/flask-app-2
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 5000
    env:
    - name: DB_USERNAME
      value: <>
    - name: DB_PASSWORD
      value: <>
    - name: DB_URL
      value: host.minikube.internal
    - name: DB_NAME
      value: flask_db
